AWSTemplateFormatVersion: '2010-09-09'
Description: 'Soccer Platform Infrastructure - 30 Days DevOps Challenge'

Parameters:
  EnvironmentName:
    Description: Environment name for resource tagging
    Type: String
    Default: dev

  VpcCIDR:
    Description: CIDR block for VPC
    Type: String
    Default: 10.0.0.0/16

Resources:
  # VPC Configuration will go here
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-vpc

Outputs:
  VPC:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPCID